language: python

python:
  - 3.5
  - 3.6.3
  - 3.6.4
  - 3.6.5
  
install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt

script:
  - nosetests -v --with-coverage --cover-package=quaternion